// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/customer": {
            "get": {
                "description": "Get home page details.",
                "produces": [
                    "application/json"
                ],
                "summary": "Get home page.",
                "operationId": "get-home-page",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/customer/profile": {
            "get": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Get details about a customer.",
                "produces": [
                    "application/json"
                ],
                "summary": "Get information about a customer.",
                "operationId": "customer-profile",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/customer/sign-in": {
            "post": {
                "description": "Customer sign in.",
                "produces": [
                    "application/json"
                ],
                "summary": "Customer sign in process.",
                "operationId": "customer-sign-in",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/customer/signup": {
            "post": {
                "description": "Create a new customer.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create a new customer.",
                "operationId": "create-customer",
                "parameters": [
                    {
                        "description": "Customer information to create",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/params.CustomerInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response_structs.CustomerResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "params.CustomerInput": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "response_structs.CustomerResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "MY Sample API",
	Description:      "Sample API description",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
