basePath: /api/v1
definitions:
  params.CustomerInput:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  response_structs.CustomerResponse:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
  description: Sample API description
  title: MY Sample API
  version: "1.0"
paths:
  /customer:
    get:
      description: Get home page details.
      operationId: get-home-page
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get home page.
  /customer/profile:
    get:
      description: Get details about a customer.
      operationId: customer-profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - BearerToken: []
      summary: Get information about a customer.
  /customer/sign-in:
    post:
      description: Customer sign in.
      operationId: customer-sign-in
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Customer sign in process.
  /customer/signup:
    post:
      consumes:
      - application/json
      description: Create a new customer.
      operationId: create-customer
      parameters:
      - description: Customer information to create
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/params.CustomerInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response_structs.CustomerResponse'
      summary: Create a new customer.
swagger: "2.0"
