basePath: /api/v1
info:
  contact: {}
  description: Sample API description
  title: MY Sample API
  version: "1.0"
paths:
  /customer:
    get:
      description: Get details about a customer.
      operationId: get-customer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get information about a customer.
swagger: "2.0"
